import streamlit as st

def app():
    st.write("")
    st.write("")
    st.write("")
    st.write("")
    st.write("")
    st.write("")
    st.write("")
    st.write("")
    st.write("")
    st.title("OMDENA FRANCE LOCAL CHAPTER 2021")
    st.write("")
    st.write("")
    st.write("")
    st.header("COVID-19 BEFORE-DURING ANALYSIS IN FRANCE")
    st.write("")
    st.write("")
    st.write("")
    st.write("Page 1: COVID-19 Data Analysis")
    st.write("Page 2: N0 Lockdown Phase")
    st.write("Page 3: First Lockdown Phase")
    st.write("Page 4: Second Lockdown Phase")
    st.write("Page 5: Third Lockdown Phase")
    st.write("Page 6: Compare Lockdown Phases")
    st.write("Page 7: Region-Wise Analysis")